type IRarityType =
  | "QUALITY_GRAY"
  | "QUALITY_GREEN"
  | "QUALITY_BLUE"
  | "QUALITY_PURPLE"
  | "QUALITY_ORANGE"
  | "QUALITY_ORANGE_SP";

type IElementType =
  | "Anemo"
  | "Geo"
  | "Electro"
  | "Dendro"
  | "Hydro"
  | "Pyro"
  | "Cryo";

type IWeaponType =
  | "WEAPON_SWORD_ONE_HAND"
  | "WEAPON_CLAYMORE"
  | "WEAPON_POLE"
  | "WEAPON_CATALYST"
  | "WEAPON_BOW";

type IBodyType =
  | "BODY_MALE"
  | "BODY_BOY"
  | "BODY_LADY"
  | "BODY_GIRL"
  | "BODY_LOLI";

type IWeaponCurve =
  | "GROW_CURVE_ATTACK_101"
  | "GROW_CURVE_ATTACK_102"
  | "GROW_CURVE_ATTACK_103"
  | "GROW_CURVE_ATTACK_104"
  | "GROW_CURVE_ATTACK_105"
  | "GROW_CURVE_CRITICAL_101"
  | "GROW_CURVE_ATTACK_201"
  | "GROW_CURVE_ATTACK_202"
  | "GROW_CURVE_ATTACK_203"
  | "GROW_CURVE_ATTACK_204"
  | "GROW_CURVE_ATTACK_205"
  | "GROW_CURVE_CRITICAL_201"
  | "GROW_CURVE_ATTACK_301"
  | "GROW_CURVE_ATTACK_302"
  | "GROW_CURVE_ATTACK_303"
  | "GROW_CURVE_ATTACK_304"
  | "GROW_CURVE_ATTACK_305"
  | "GROW_CURVE_CRITICAL_301";

type EquipType =
  | "EQUIP_BRACER"
  | "EQUIP_NECKLACE"
  | "EQUIP_SHOES"
  | "EQUIP_RING"
  | "EQUIP_DRESS";
